    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm' # 开启自动缓存，加速后续构建

      - name: Install dependencies
        shell: bash
        run: |
          # 针对 Windows 权限问题的预处理
          npm config set fund false
          npm install
        env:
          # 确保 Electron 走 GitHub 官方快速通道
          ELECTRON_MIRROR: "https://github.com"

      - name: Build and Release
        run: npm run electron:build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # 某些打包工具也需要在 build 阶段设置此变量
          ELECTRON_MIRROR: "https://github.com"
